ITEM_COUNT_PER_PAGE = 6
PAGER_INDICATOR_LENGTH = 5

CODE_LOGIN_REQUIRED = 1
CODE_PARAMS_WRONG = 2

ERROR_CODE_AND_MESSAGE_DICT = {
    CODE_LOGIN_REQUIRED: 'login required',
    CODE_PARAMS_WRONG: 'params wrong',
}