ITEM_COUNT_PER_PAGE_ = 6
ITEM_COUNT_PER_PAGE_FOR_SET = 6
ITEM_COUNT_PER_PAGE_MYPAGE_INTEREST_PRODUCT = 9
ITEM_COUNT_PER_PAGE_MYPAGE_INTEREST_SET = 6

PAGER_INDICATOR_LENGTH = 5

CODE_LOGIN_REQUIRED = 1
CODE_PARAMS_WRONG = 2

ERROR_CODE_AND_MESSAGE_DICT = {
    CODE_LOGIN_REQUIRED: 'login required',
    CODE_PARAMS_WRONG: 'params wrong',
}